// Generated by LiveScript 1.3.1
var x$;
x$ = angular.module('yslin');
x$.controller('navbar', function($scope){
  $scope.showicon = 0;
  return $scope.iconToggle = function(v){
    return $scope.navToggle = v;
  };
});