// Generated by LiveScript 1.3.1
var x$;
x$ = angular.module('yslin');
x$.controller('white', function($scope, $timeout){
  var melistRange;
  $scope.video = document.getElementById("liu-201");
  $scope.videoPlaying = false;
  /*
  $timeout ->
    video.play!
    console.log video
  , 2000
  */
  $scope.render = function(){
    var s, wh, top, h;
    s = skrollr.get().getScrollTop();
    wh = $(window).height();
    if (!$scope.video) {
      return;
    }
    top = $($scope.video).position().top;
    h = $($scope.video).height();
    if (s + wh > top && s < top + h && $scope.video.paused) {
      $scope.video.play();
    }
    if (s > top + h && !$scope.video.paused) {
      return $scope.video.pause();
    }
  };
  melistRange = [[0, 120], [120, 350], [350, 510], [510, 695], [695, 900], [900, 1120], [1120, 1400]].map(function(it){
    return [it[0] / 1440, it[1] / 1440];
  });
  console.log(melistRange);
  $scope.melistTab = 0;
  return $scope.melist = function(e){
    var p, ret;
    p = e.clientX / $(window).width();
    ret = melistRange.map(function(d, i){
      if (d[0] <= p && d[1] >= p) {
        return i;
      } else {
        return -1;
      }
    }).filter(function(it){
      return it >= 0;
    });
    return $scope.melistTab = ret.length <= 0
      ? 0
      : ret[0] + 1;
  };
});